Google auth (#31)
Slack_web_hooks

diff --git a/.github/workflows/frontend.yml b/.github/workflows/frontend.yml
--- a/.github/workflows/frontend.yml
+++ b/.github/workflows/frontend.yml
@@ -26,23 +26,31 @@ jobs:
             git pull origin main
             export PATH=$PATH:/root/.nvm/versions/node/v18.16.0/bin
             pm2 restart frontend
-  slackNotification:
-    needs: [ "deploy" ]
-    name: Slack Notification
-    runs-on: ubuntu-latest
+  send_notification_to_slack:
+    name: Send notification to Slack
+    runs-on: ubuntu-22.04
+    if: always()
+    needs: [job_a, job_b]
     steps:
-      - name: My first step
-        uses: docker://alpine:3.8
-      - uses: actions/checkout@v2
-      - name: Slack Notification
-        uses: slackapi/slack-github-action@v1.24.0
-        with:
-          # Slack channel id, channel name, or user id to post message.
-          # See also: https://api.slack.com/methods/chat.postMessage#channels
-          # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
-          channel-id: 'agristroom-development'
-          # For posting a simple plain text message
-          slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
-        env:
-          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
-
+      - run: |
+          successText=":octocat: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Build #${{ github.run_number }}> of *${{ github.repository }}@${{ github.ref_name }}* by *${{ github.actor }}* completed successfully."
+          failureText=":octocat: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Build #${{ github.run_number }}> of *${{ github.repository }}@${{ github.ref_name }}* by *${{ github.actor }}* failed."
+          cancelledText=":octocat: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Build #${{ github.run_number }}> of *${{ github.repository }}@${{ github.ref_name }}* by *${{ github.actor }}* was cancelled.😥"
+          status="${{ (contains(needs.*.result, 'cancelled') && 'cancelled') || (contains(needs.*.result, 'failure') && 'failure') || 'success' }}"
+          
+          if [ "$status" = 'success' ]; then
+           color='good'
+           text=$successText
+          elif [ "$status" = 'failure' ]; then
+           color='danger'
+           text=$failureText
+          elif [ "$status" = "cancelled" ]; then
+            color='warning'
+            text=$cancelledText
+          fi
+          
+          echo "{attachments: [{text: \"$text\", color: \"$color\"}]}" | curl \
+            "${{ secrets.SLACK_WEBHOOK_URL }}" \
+            -X "POST" \
+            --header "Content-Type: application/json" \
+            --data-binary @-
